unleash:
  image:
    repo: gcr.io/bricks-software-public/unleash-enterprise
    tag: latest
postgresql:
  image: gcr.io/bricks-software-public/unleash-enterprise/postgresql:latest
  exporter:
    image: null
  db:
    password: null
    name: unleash
    user: unleash
metrics:
  image: gcr.io/bricks-software-public/unleash-enterprise/prometheus-to-sd:latest
  exporter:
    enabled: flalse
deployer:
  image: null
ubbagent:
  name: unleash-ubbagent
  image: gcr.io/bricks-software-public/unleash-enterprise/ubbagent
reportingSecret: null
